# DEPLOY IMAGE
FROM node:22-alpine

RUN apk add --no-cache tzdata

COPY meteor/bundle /opt/core
COPY meteor/docker-entrypoint.sh /opt
WORKDIR /opt/core
RUN chown -R 1000:1000 /opt/core
USER 1000
CMD ["/opt/docker-entrypoint.sh"]
