openapi: '3.0.3'
info:
  title: 'Sofie User Actions API'
  description: 'The Sofie User Actions API provides paths to allow a device to control a Sofie and query health information'
  version: '0.0.1'
  license:
    name: 'MIT License'
    url: 'http://opensource.org/licenses/MIT'
servers:
  - url: http://localhost:3000/api2
    description: Initial release of UserActions API - http - for use during development only!
tags:
  - name: userActions
    description: Provides the ability to control the Sofie application
paths:
  /:
    $ref: 'definitions/sofie.yaml#/resources/index'
  # playlist operations
  /playlists/{playlistId}/activate:
    $ref: 'definitions/playlists.yaml#/resources/activate'
  /playlists/{playlistId}/deactivate:
    $ref: 'definitions/playlists.yaml#/resources/deactivate'
  /playlists/{playlistId}/executeAdLib:
    $ref: 'definitions/playlists.yaml#/resources/executeAdLib'
  /playlists/{playlistId}/moveNextPart:
    $ref: 'definitions/playlists.yaml#/resources/moveNextPart'
  /playlists/{playlistId}/moveNextSegment:
    $ref: 'definitions/playlists.yaml#/resources/moveNextSegment'
  /playlists/{playlistId}/reloadPlaylist:
    $ref: 'definitions/playlists.yaml#/resources/reloadPlaylist'
  /playlists/{playlistId}/resetPlaylist:
    $ref: 'definitions/playlists.yaml#/resources/resetPlaylist'
  /playlists/{playlistId}/setNextPart:
    $ref: 'definitions/playlists.yaml#/resources/setNextPart'
  /playlists/{playlistId}/setNextSegment:
    $ref: 'definitions/playlists.yaml#/resources/setNextSegment'
  /playlists/{playlistId}/take:
    $ref: 'definitions/playlists.yaml#/resources/take'
  /playlists/{playlistId}/sourceLayer/{sourceLayerId}':
    $ref: 'definitions/playlists.yaml#/resources/sourceLayer'
  /playlists/{playlistId}/sourceLayer/{sourceLayerId}/recallSticky:
    $ref: 'definitions/playlists.yaml#/resources/recallSticky'
  # studio operations
  /studios/{studioId}/switchRouteSet:
    $ref: 'definitions/studios.yaml#/resources/switchRouteSet'
