export interface RestAPIAdLibActions {}
export interface RestAPIAdLibPieces {}
export interface RestAPIBlueprints {}
export interface RestAPIBucketAdlibActions {}
export interface RestAPIBucketAdlibs {}
export interface RestAPIBuckets {}
export interface RestAPICoreSystem {}
export interface RestAPIEvaluations {}
export interface RestAPIExpectedMediaItems {}
export interface RestAPIExpectedPackages {}
export interface RestAPIExpectedPackageWorkStatuses {}
export interface RestAPIExpectedPlayoutItems {}
export interface RestAPIExternalMessageQueue {}
export interface RestAPIIngestDataCache {}
export interface RestAPIMediaObjects {}
export interface RestAPIMediaWorkFlows {}
export interface RestAPIMediaWorkFlowSteps {}
export interface RestAPIOrganization {}
export interface RestAPIPackageContainerPackageStatus {}
export interface RestAPIPackageInfos {}
export interface RestAPIPartInstances {}
export interface RestAPIParts {}
export interface RestAPIPeripheralDeviceCommands {}
export interface RestAPIPeripheralDevices {}
export interface RestAPIPieceInstances {}
export interface RestAPIPieces {}
export interface RestAPIRundownBaselineAdLibActions {}
export interface RestAPIRundownBaselineAdLibPieces {}
export interface RestAPIRundownBaselineObjs {}
export interface RestAPIRundownLayouts {}
export interface RestAPIRundownPlaylists {}
export interface RestAPIRundowns {}
export interface RestAPISegments {}
export interface RestAPIShowStyleBases {}
export interface RestAPIShowStyleVariants {}
export interface RestAPISnapshots {}
export interface RestAPIStudios {}
export interface RestAPITimeline {}
export interface RestAPIUserActionsLog {}
export interface RestAPIUsers {}
export interface RestAPITriggeredActions {}
