window.glossary = [
  ['.link', 'Makes any element (even buttons) look like a link'],
  ['.clickable', 'Hints that an element is clickable with the right cursor'],
  ['.nw', 'Sets white-space to nowrap'],
  ['.wb', 'Sets word-break to break-all'],
  ['.btn', 'Creates a button.', 'buttons'],
  ['.btn-secondary', 'Modifies a button.', 'buttons'],
  ['.btn-subtle', 'Modifies a button.', 'buttons'],
  ['.btn-primary', 'Modifies a button.', 'buttons'],
  ['.btn-big', 'Modifies a button.', 'buttons'],
  ['.btn-compact', 'Modifies a button.', 'buttons'],
  ['.action', 'Creates a button that doesn\'t look like one', 'actions'],
  ['.action-btn', 'Creates a button that doesn\'t look like one', 'actions'],
  ['.action-item', 'The content of an action button', 'actions'],
  ['.action-vb', 'A baseline-aligned action', 'actions'],
  ['.text-link', 'Links that are basically undetectable'],
  ['.pill', 'Creates a pill (e.g. for tags etc)', 'pills'],
  ['.pills', 'Groups and alignes a list of pills', 'pills'],
  ['.pill-action', 'An action inside a pill', 'pills'],
  ['.pill-hl', 'A highlighted pill', 'pills'],
  ['.pill-dp', 'A downplayed pill', 'pills'],
  ['.notifications', 'Wrapper for notification bubbles', 'notifications'],
  ['.notification-count', 'Number of notifications', 'notifications'],
  ['.round', '', 'round-objects'],
  ['.ctx-menu', '', 'ctx-menu'],
  ['.readable', 'Sets a max-width on paragraphs', 'body-text'],
  ['.readable-l', 'Sets a larger max-width on paragraphs', 'body-text'],
  ['.tweecon', 'Not currently in use', 'tweecon'],
  ['.tweecon-state', '', 'tweecon'],
  ['.ts1', '', 'tweecon'],
  ['.ts2', '', 'tweecon'],
  ['.tweecon-active', '', 'tweecon'],
  ['.bi', 'Big inputs (e.g. Radioarkivets search input)', 'big-input'],
  ['.bi-input', 'The input in a big input', 'big-input'],
  ['.bi-action', 'Actions (such as clear) in big inputs', 'big-input'],
  ['.highlight', 'Highlights words, e.g. search terms'],
  ['.selected-item', 'Grey selection square', 'overlays'],
  ['.expco', '', 'expco'],
  ['.expco-expand', 'Expand/collapse button', 'expco'],
  ['.expco-title', 'Title/selected text', 'expco'],
  ['.expco-body', 'Expanded body', 'expco'],
  ['.expco-item', 'An item in the expanded body', 'expco'],
  ['.border-box', 'Shadowed box for overlays', 'overlays'],
  ['.overlay-m', 'Medium sized overlay', 'overlays'],
  ['.overlay-s', 'Small sized overlay', 'overlays'],
  ['.switch', '', 'switches'],
  ['.switch-active', '', 'switches'],
  ['.cal-year', '', 'datepicker'],
  ['.cal-table', '', 'datepicker'],
  ['.cal-selected', '', 'datepicker'],
  ['.cal-year', '', 'datepicker'],
  ['.cal-selected-mon', '', 'datepicker'],
  ['.kb-nav-current', 'Keyboard navigation outline'],
  ['.ic', '', 'index-copy'],
  ['.ic-label', '', 'index-copy'],
  ['.progress-bar', '', 'progress-bar'],
  ['.pb-track', '', 'progress-bar'],
  ['.pb-indicator', '', 'progress-bar'],
  ['.one-liner', 'One line of text with ellipsis overflow', 'oneliners'],
  ['.subtle', 'Subtle text, lighter color'],
  ['.vsubtle', 'Very subtle text, very light color'],
  ['.dimmed', 'Even lighter than very subtle - do not use when legibility is important'],
  ['.removed', 'Like dimmed, but with a line through'],
  ['.bghl', 'Highlighted background - yellow'],
  ['.warn', 'Red background, dark text'],
  ['.bg-subtle', 'Grey background'],
  ['.bg-vsubtle', 'Light grey background'],
  ['.sr-only', 'Text that is only intended for screen-readers (e.g. text for icons)'],
  ['.dark', 'Enables the dark theme for an element'],
  ['.select', 'Wraps a select box', 'forms'],
  ['.inline-select', 'Border-less select', 'forms'],
  ['.text-input', '', 'forms'],
  ['.field', 'For label/input pairs', 'forms'],
  ['.input-s', 'Small inputs', 'forms'],
  ['.input-m', 'Medium inputs', 'forms'],
  ['.input-l', 'Wide inputs', 'forms'],
  ['.input-full', 'Full-width inputs', 'forms'],
  ['.mdi', 'Material design-inspired inputs', 'inputs'],
  ['.mdinput', '', 'inputs'],
  ['.mdi-focus', '', 'inputs'],
  ['.mdfx', '', 'inputs'],
  ['.edit-action', '', 'inputs'],
  ['.perma-action', '', 'inputs'],
  ['.view-action', '', 'inputs'],
  ['.mdfx-hl', '', 'inputs'],
  ['.error', 'Wraps and modifies form inputs', 'forms'],
  ['.error-msg', 'Used for field-based error messages', 'inputs'],
  ['.elastic-input', 'Expanding inputs/textareas', 'elastic-inputs'],
  ['.sizer', '', 'elastic-inputs'],
  ['.focusable', 'Elements that can catch focus'],
  ['.range', 'Use on range inputs'],
  ['.icon', 'An SVG icon', 'icons'],
  ['.logo', 'An SVG logo', 'logos'],
  ['.icon-l', 'Large icon', 'icons'],
  ['.icon-xl', 'Extra large icon', 'icons'],
  ['.icon-xxl', 'Seriously large icon', 'icons'],
  ['.icon-hl', 'Highlighted icon', 'icons'],
  ['.mod', 'Gives a div block semantics (margins)', 'layout'],
  ['.tight-s', 'Reduces the amount of vertical spacing on block elements', 'layout'],
  ['.tight-xs', 'Further reduces the amount of vertical spacing on block elements', 'layout'],
  ['.tight-none', 'Removes vertical spacing on block elements', 'layout'],
  ['.unrelated', 'Provides horizontal spacing for nested <code>.item</code> elements', 'layout'],
  ['.related', 'Provides horizontal spacing for nested <code>.item</code> elements', 'layout'],
  ['.item', 'Used inside <code>.related</code> or <code>.unrelated</code>', 'layout'],
  ['.right', 'Floats element right', 'layout'],
  ['.left', 'Floats element left', 'layout'],
  ['.clear', 'Clears floats', 'layout'],
  ['.row', 'Grid layout row', 'layout'],
  ['.col', 'Grid layout column', 'layout'],
  ['.c1',  'Span 1 column', 'layout'],
  ['.c2',  'Span 2 columns', 'layout'],
  ['.c3',  'Span 3 columns', 'layout'],
  ['.c4',  'Span 4 columns', 'layout'],
  ['.c5',  'Span 5 columns', 'layout'],
  ['.c6',  'Span 6 columns', 'layout'],
  ['.c7',  'Span 7 columns', 'layout'],
  ['.c8',  'Span 8 columns', 'layout'],
  ['.c9',  'Span 9 columns', 'layout'],
  ['.c10', 'Span 10 columns', 'layout'],
  ['.c11', 'Span 11 columns', 'layout'],
  ['.c1-of-24', 'Span half a column', 'layout'],
  ['.rm-c1', 'Span 1 column on medium screens and up', 'layout'],
  ['.rm-c2', 'Span 2 columns on medium screens and up', 'layout'],
  ['.rm-c3', 'Span 3 columns on medium screens and up', 'layout'],
  ['.rm-c4', 'Span 4 columns on medium screens and up', 'layout'],
  ['.rm-c5', 'Span 5 columns on medium screens and up', 'layout'],
  ['.rm-c6', 'Span 6 columns on medium screens and up', 'layout'],
  ['.rm-c7', 'Span 7 columns on medium screens and up', 'layout'],
  ['.rm-c8', 'Span 8 columns on medium screens and up', 'layout'],
  ['.rm-c9', 'Span 9 columns on medium screens and up', 'layout'],
  ['.rm-c10', 'Span 10 columns on medium screens and up', 'layout'],
  ['.rm-c11', 'Span 11 columns on medium screens and up', 'layout'],
  ['.rm-s1-5', 'Makes grid column 1/5 wide on medium screens and up', 'layout'],
  ['.rm-s1-7', 'Makes grid column 1/7 wide on medium screens and up', 'layout'],
  ['.rl-c1', 'Span 1 column on large screens and up', 'layout'],
  ['.rl-c2', 'Span 2 columns on large screens and up', 'layout'],
  ['.rl-c3', 'Span 3 columns on large screens and up', 'layout'],
  ['.rl-c4', 'Span 4 columns on large screens and up', 'layout'],
  ['.rl-c5', 'Span 5 columns on large screens and up', 'layout'],
  ['.rl-c6', 'Span 6 columns on large screens and up', 'layout'],
  ['.rl-c7', 'Span 7 columns on large screens and up', 'layout'],
  ['.rl-c8', 'Span 8 columns on large screens and up', 'layout'],
  ['.rl-c9', 'Span 9 columns on large screens and up', 'layout'],
  ['.rl-c10', 'Span 10 columns on large screens and up', 'layout'],
  ['.rl-c11', 'Span 11 columns on large screens and up', 'layout'],
  ['.rl-s1-5', 'Makes grid column 1/5 wide on large screens and up', 'layout'],
  ['.rl-s1-7', 'Makes grid column 1/7 wide on large screens and up', 'layout'],
  ['.rxl-c1', 'Span 1 column on extra large screens and up', 'layout'],
  ['.rxl-c2', 'Span 2 columns on extra large screens', 'layout'],
  ['.rxl-c3', 'Span 3 columns on extra large screens', 'layout'],
  ['.rxl-c4', 'Span 4 columns on extra large screens', 'layout'],
  ['.rxl-c5', 'Span 5 columns on extra large screens', 'layout'],
  ['.rxl-c6', 'Span 6 columns on extra large screens', 'layout'],
  ['.rxl-c7', 'Span 7 columns on extra large screens', 'layout'],
  ['.rxl-c8', 'Span 8 columns on extra large screens', 'layout'],
  ['.rxl-c9', 'Span 9 columns on extra large screens', 'layout'],
  ['.rxl-c10', 'Span 10 columns on extra large screens', 'layout'],
  ['.rxl-c11', 'Span 11 columns on extra large screens', 'layout'],
  ['.rxl-s1-5', 'Makes grid column 1/5 wide on extra large screens', 'layout'],
  ['.rxl-s1-7', 'Makes grid column 1/7 wide on extra large screens', 'layout'],
  ['.s1-5', 'Makes grid column 1/5 wide', 'layout'],
  ['.s1-7', 'Makes grid column 1/7 wide', 'layout'],
  ['.bd', 'Gives an element a separate formatting context, traps margins and clears floats', 'media'],
  ['.grid-unit', 'Inline block box with set width', 'responsive-grids'],
  ['.grid-box', 'Inline block box', 'responsive-grids'],
  ['.gu-l', 'Large inline block box', 'responsive-grids'],
  ['.container', 'Relatively positioned, used to contain positioned elements'],
  ['.pos-tr', 'Absolutely positioned, top right corner'],
  ['.media', 'Container for media elements', 'media'],
  ['.media-elem', 'Left-aligned media element', 'media'],
  ['.media-elem-ext', 'Right-aligned media element', 'media'],
  ['.show-m', 'Only show on medium screens and up'],
  ['.show-l', 'Only show on large screens and up'],
  ['.show-xl', 'Only show on extra large screens'],
  ['.rm-right', 'Float right on medium screens and up'],
  ['.rm-left', 'Float left on medium screens and up'],
  ['.rl-right', 'Float right on large screens and up'],
  ['.rl-left', 'Float left on large screens and up'],
  ['.man', 'No margins'],
  ['.mhn', 'No horizontal margins'],
  ['.mvn', 'No vertical margins'],
  ['.mrn', 'No right-margin'],
  ['.mtn', 'No top-margin'],
  ['.mbn', 'No bottom-margin'],
  ['.mln', 'No left-margin'],
  ['.mas', 'Small margins'],
  ['.mhs', 'Small horizontal margins'],
  ['.mvs', 'Small vertical margins'],
  ['.mrs', 'Small right-margin'],
  ['.mts', 'Small top-margin'],
  ['.mbs', 'Small bottom-margin'],
  ['.mls', 'Small left-margin'],
  ['.mam', 'Medium margins'],
  ['.mhm', 'Medium horizontal margins'],
  ['.mvm', 'Medium vertical margins'],
  ['.mrm', 'Medium right-margin'],
  ['.mtm', 'Medium top-margin'],
  ['.mbm', 'Medium bottom-margin'],
  ['.mlm', 'Medium left-margin'],
  ['.mal', 'Large margins'],
  ['.mhl', 'Large horizontal margins'],
  ['.mvl', 'Large vertical margins'],
  ['.mrl', 'Large right-margin'],
  ['.mtl', 'Large top-margin'],
  ['.mbl', 'Large bottom-margin'],
  ['.mll', 'Large left-margin'],
  ['.pan', 'No padding'],
  ['.phn', 'No horizontal padding'],
  ['.pvn', 'No vertical padding'],
  ['.prn', 'No right-padding'],
  ['.ptn', 'No top-padding'],
  ['.pbn', 'No bottom-padding'],
  ['.pln', 'No left-padding'],
  ['.pas', 'Small padding'],
  ['.phs', 'Small horizontal padding'],
  ['.pvs', 'Small vertical padding'],
  ['.prs', 'Small right-padding'],
  ['.pts', 'Small top-padding'],
  ['.pbs', 'Small bottom-padding'],
  ['.pls', 'Small left-padding'],
  ['.pam', 'Medium padding'],
  ['.phm', 'Medium horizontal padding'],
  ['.pvm', 'Medium vertical padding'],
  ['.prm', 'Medium right-padding'],
  ['.ptm', 'Medium top-padding'],
  ['.pbm', 'Medium bottom-padding'],
  ['.plm', 'Medium left-padding'],
  ['.pal', 'Large padding'],
  ['.phl', 'Large horizontal padding'],
  ['.pvl', 'Large vertical padding'],
  ['.prl', 'Large right-padding'],
  ['.ptl', 'Large top-padding'],
  ['.pbl', 'Large bottom-padding'],
  ['.pll', 'Large left-padding'],
  ['.table', 'Full-width table', 'tables'],
  ['.table-discrete', 'Border-less table', 'tables'],
  ['.table-spaced', '', 'tables'],
  ['.compact', 'Table cells that are only wide enough to fit their content', 'tables'],
  ['.expando', 'Expanding table', 'tables'],
  ['.expando-tight', 'Tighter expanding table', 'tables'],
  ['.hl', 'Highlights rows in tables', 'tables'],
  ['.expando-details', 'Expanded part of expanding tables', 'tables'],
  ['.expando-addon', 'Additional no-space row in expando table', 'tables'],
  ['.h1', 'Apply h1-style typography to anything'],
  ['.h2', 'Apply h2-style typography to anything'],
  ['.h3', 'Apply h3-style typography to anything'],
  ['.h4', 'Apply h4-style typography to anything'],
  ['.h5', 'Apply h5-style typography to anything'],
  ['.h6', 'Apply h6-style typography to anything'],
  ['.text-s', 'Small text'],
  ['.text-xs', 'Very small text'],
  ['.text-m', 'Medium text'],
  ['.text-l', 'Large text'],
  ['.strong', 'Strong text'],
  ['.alright', 'Right-aligned text'],
  ['.alc', 'Center-aligned text'],
  ['.disable-select', 'Prevents text selection'],
  ['.inline-block', 'Inline block element'],
  ['.hide', 'Hides an element'],
  ['.show', 'Shows an element, inherits display'],
  ['.hide-s-up', 'Hides an element for size s and up'],
  ['.show-s-up', 'Shows an element for size s and up, inherits display'],
  ['.hide-m-up', 'Hides an element for size m and up'],
  ['.show-m-up', 'Shows an element for size m and up, inherits display'],
  ['.hide-l-up', 'Hides an element for size l and up'],
  ['.show-l-up', 'Shows an element for size l and up, inherits display'],
  ['.hide-xl-up', 'Hides an element for size xl and up'],
  ['.show-xl-up', 'Shows an element for size xl and up, inherits display'],
  ['.invisible', 'Hides an element using "visibility: hidden"'],
  ['.alb', 'Vertical align bottom'],
  ['.disabled', 'Sets element to disabled-color'],
  ['.gutter', 'Provides extra horizontal space on large screens. To be used on the outermost layers of your page.']
];
