export enum LLayers {
	casparcg_player_vignett = 'casparcg_player_vignett',
	casparcg_player_clip = 'casparcg_player_clip',
	casparcg_cg_graphics = 'casparcg_cg_graphics',
	casparcg_cg_logo = 'casparcg_cg_logo',
	casparcg_cg_studiomonitor = 'casparcg_cg_studiomonitor',
	lawo_source_effect = 'lawo_source_effect',
	lawo_source_automix = 'lawo_source_automix',
	lawo_source_clip = 'lawo_source_clip',
	atem_me_program = 'atem_me_program',
	casparcg_player_wipe = 'casparcg_player_wipe',
	casparcg_player_soundeffect = 'casparcg_player_soundeffect',
	atem_me_studiomonitor = 'atem_me_studiomonitor',
	atem_aux_clean = 'atem_aux_clean',
	atem_aux_preview = 'atem_aux_preview',
	atem_dsk_effect = 'atem_dsk_effect',
	atem_dsk_graphics = 'atem_dsk_graphics',
	lawo_source_preview = 'lawo_source_preview',
}