/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gettingStarted: [{ type: 'autogenerated', dirName: 'getting-started' }],
  forDevelopers: [{ type: 'autogenerated', dirName: 'for-developers' }],
  main: [{ type: 'autogenerated', dirName: 'main' }],
  
  // fallback 
  // default: [{ type: 'autogenerated', dirName: '.' }],
  

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
