/**
 * This file is the entry-point for both server side and client side code
 */

import './collections/AdLibPieces'
import './collections/AsRunLog'
import './collections/Blueprints'
import './collections/Evaluations'
import './collections/ExpectedMediaItems'
import './collections/ExpectedPlayoutItems'
import './collections/ExternalMessageQueue'
import './collections/IngestDataCache'
import './collections/MediaObjects'
import './collections/MediaWorkFlows'
import './collections/MediaWorkFlowSteps'
import './collections/PartInstances'
import './collections/Parts'
import './collections/PeripheralDeviceCommands'
import './collections/PeripheralDevices'
import './collections/PieceInstances'
import './collections/Pieces'
import './collections/RundownBaselineAdLibPieces'
import './collections/RundownBaselineObjs'
import './collections/RundownLayouts'
import './collections/RundownPlaylists'
import './collections/Rundowns'
import './collections/Segments'
import './collections/ShowStyleBases'
import './collections/ShowStyleVariants'
import './collections/Snapshots'
import './collections/Studios'
import './collections/Timeline'
import './collections/UserActionsLog'

import './Settings'
import './systemTime'
