/**
 * This file is the entry-point for both server side and client side code
 */

import './collections/AdLibActions'
import './collections/AdLibPieces'
import './collections/Blueprints'
import './collections/BucketAdlibActions'
import './collections/BucketAdlibs'
import './collections/Buckets'
import './collections/CoreSystem'
import './collections/Evaluations'
import './collections/ExpectedMediaItems'
import './collections/ExpectedPackages'
import './collections/ExpectedPackageWorkStatuses'
import './collections/ExpectedPlayoutItems'
import './collections/ExternalMessageQueue'
import './collections/MediaObjects'
import './collections/MediaWorkFlows'
import './collections/MediaWorkFlowSteps'
import './collections/Organization'
import './collections/PackageContainerPackageStatus'
import './collections/PackageInfos'
import './collections/PartInstances'
import './collections/Parts'
import './collections/PeripheralDeviceCommands'
import './collections/PeripheralDevices'
import './collections/PieceInstances'
import './collections/Pieces'
import './collections/RundownBaselineAdLibActions'
import './collections/RundownBaselineAdLibPieces'
import './collections/RundownLayouts'
import './collections/RundownPlaylists'
import './collections/Rundowns'
import './collections/Segments'
import './collections/ShowStyleBases'
import './collections/ShowStyleVariants'
import './collections/Snapshots'
import './collections/Studios'
import './collections/Timeline'
import './collections/UserActionsLog'
import './collections/Users'
import './collections/TriggeredActions'

import './Settings'
import './systemTime'
