#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# lint meteor
cd meteor

if echo "$OSTYPE" | grep -E -q "msys|cygwin" ; then
	# we're on a windows machine
	meteor.bat npx --no-install lint-staged
elif echo "$OSTYPE" | grep -q "darwin" && arch | grep -q "arm64" ; then
	# we're on an arm64 mac
	arch -x86_64 meteor npx --no-install lint-staged
else
	meteor npx --no-install lint-staged
fi;

# lint the packages
cd ../packages
yarn lerna run --concurrency 1 --stream precommit --exclude-dependents
