#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# lint meteor
cd meteor

# check if we're on a windows machine
DUMMY=$(command -v where)
IS_WINDOWS=$?

if [ "$IS_WINDOWS" = "0" ]; then
	meteor.bat npx --no-install lint-staged
else
	meteor npx --no-install lint-staged
fi;

# lint the packages
cd ../packages
yarn lerna run --concurrency 1 --stream precommit --exclude-dependents
